# Generated by Django 4.1.3 on 2023-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_options_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
